version: '3.4'

services:
  esourcingdb:
    image: mongo


  esourcingsoln.account:
    image: ${DOCKER_REGISTRY-}esourcingsolnaccount
    build:
      context: .
      dockerfile: ESourcingSoln.Account/Dockerfile

  esourcingsoln.products:
    image: ${DOCKER_REGISTRY-}esourcingsolnproducts
    build:
      context: .
      dockerfile: ESourcingSoln.Products/Dockerfile

  esourcingsoln.sourcing:
    image: ${DOCKER_REGISTRY-}esourcingsolnsourcing
    build:
      context: .
      dockerfile: ESourcingSoln.Sourcing/Dockerfile

